# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do



  desc "Submit a new Internal app for test"
  lane :internal do
    gradle(task: 'bundle', build_type: 'Release')
     upload_to_play_store(
       track: 'internal',
       aab: '../build/app/outputs/bundle/release/app-release.aab',
       version_code: flutter_version()["version_code"],
       skip_upload_screenshots: true,
       skip_upload_images: true
       )
      rescue => exception
      raise exception unless exception.message.include?('apkNotificationMessageKeyUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
